bundler_args: --without system_tests
script: ['bundle exec rake validate','bundle exec rake lint','bundle exec rake spec SPEC_OPTS="--format documentation"','bundle exec rake metadata']
matrix:
  allow_failures:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 4.0"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 4.0"
  - rvm: 2.1.5
    env: PUPPET_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.5
    env: PUPPET_VERSION="~> 4.0"
  - rvm: 2.1.5
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 2.2.3
    env: PUPPET_VERSION="~> 4.0"


notifications:
  email: false
deploy:
  provider: puppetforge
  user: CERNOps
  password:
    secure: ni/Jf3l9777GHv0FzJUk3TLkcAaUC/tjQw2bFr7bji6V5Nh8xXhih/byIssyZwnfqNq9pf2/8jafuFpcQfyy0XsLlS4dr60QVz4AN/eEhDoO5YWH6uErUpxV7Hz4ck+ZCGwd1GpzhAPDr9tSamKY5y/Cq9GeHGGkOyLBjKIavEc=
  on:
    tags: true
    all_branches: true
    rvm: 1.9.3
    condition: $FUTURE_PARSER = yes


